tap "blacktop/tap"
tap "charmbracelet/tap"
tap "jandedobbeleer/oh-my-posh"
tap "oven-sh/bun"
brew "bat"
brew "colima", restart_service: :changed
brew "docker"
brew "eza"
brew "fzf"
brew "gh"
brew "git-lfs"
brew "glow"
brew "gnupg"
brew "go"
brew "mas"
brew "neovim"
brew "node"
brew "pinentry-mac"
brew "ripgrep"
brew "stow"
brew "stylua"
brew "thefuck"
brew "zinit"
brew "zoxide"
brew "blacktop/tap/ipsw"
brew "charmbracelet/tap/freeze"
brew "charmbracelet/tap/mods"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "oven-sh/bun/bun"
cask "1password"
cask "1password-cli"
cask "aldente"
cask "chatgpt"
cask "discord"
cask "font-departure-mono"
cask "font-maple-mono"
cask "font-monaspace"
cask "ghostty"
cask "nvidia-geforce-now"
cask "pearcleaner"
cask "roblox"
cask "sf-symbols"
cask "spotify"
cask "steam"
cask "visual-studio-code"
cask "xcodes"
mas "1Password for Safari", id: 1569813296
mas "Developer", id: 640199958
mas "Helm", id: 6479357934
mas "Refined GitHub", id: 1519867270
mas "SponsorBlock", id: 1573461917
mas "TestFlight", id: 899247664
mas "Userscripts", id: 1463298887
mas "Wappalyzer - Technology profiler", id: 1520333300
mas "WhatsApp", id: 310633997
mas "Wipr", id: 1662217862