tap "charmbracelet/tap"
tap "jandedobbeleer/oh-my-posh"
tap "oven-sh/bun"
brew "act"
brew "bat"
brew "colima", restart_service: :changed
brew "docker"
brew "eza"
brew "fzf"
brew "gh"
brew "git-lfs"
brew "glow"
brew "gnupg"
brew "go"
brew "httpie"
brew "mas"
brew "neovim"
brew "node"
brew "ripgrep"
brew "stow"
brew "stylua"
brew "thefuck"
brew "tmux"
brew "tpm"
brew "zinit"
brew "zoxide"
brew "charmbracelet/tap/freeze"
brew "charmbracelet/tap/mods"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "oven-sh/bun/bun"
cask "1password-cli@beta"
cask "1password@nightly"
cask "aldente"
cask "discord"
cask "font-departure-mono"
cask "font-maple-mono"
cask "font-monaspace"
cask "ghostty"
cask "lunar-client"
cask "nvidia-geforce-now"
cask "pearcleaner"
cask "raycast"
cask "sf-symbols"
cask "sketch@beta"
cask "steam"
cask "tower"
cask "visual-studio-code"
cask "xcodes"
mas "1Password for Safari", id: 1569813296
mas "Developer", id: 640199958
mas "HazeOver", id: 430798174
mas "Helm", id: 6479357934
mas "Raycast Companion", id: 6738274497
mas "Refined GitHub", id: 1519867270
mas "SponsorBlock", id: 1573461917
mas "TestFlight", id: 899247664
mas "Userscripts", id: 1463298887
mas "Wappalyzer - Technology profiler", id: 1520333300
mas "WhatsApp", id: 310633997
mas "Wipr", id: 1662217862